# Generated by Django 5.0.6 on 2024-07-29 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_checklistassignment_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklistassignment',
            name='group_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='checklist.role'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistassignment',
            unique_together={('checklist', 'group_assigned')},
        ),
    ]
