# Generated by Django 5.0.6 on 2024-08-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_checklistassignment_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistexecution',
            unique_together={('checklist', 'start_at')},
        ),
    ]
