# Generated by Django 5.0.6 on 2024-08-01 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_checklistexecution_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistexecution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistexecution',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='checklistexecution',
            unique_together={('checklist', 'start_date')},
        ),
    ]
